# Generated by Django 3.2.8 on 2021-10-15 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_bookie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('league', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('home_team', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team', models.CharField(blank=True, max_length=100, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('bet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('odd', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stake', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bookie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bookie')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.match')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
