# Generated by Django 3.2.8 on 2021-11-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20211101_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='oddspedia_match_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
