# Generated by Django 3.2.8 on 2021-12-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_match_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['match']},
        ),
    ]
