# Generated by Django 3.2.8 on 2021-11-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_bookie_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookie',
            name='name',
            field=models.CharField(blank=True, choices=[('bet-at-home', 'Bet-At-Home'), ('bet365', 'Bet365'), ('betway', 'Betway'), ('bwin', 'Bwin'), ('interwetten', 'Interwetten'), ('unibet', 'Unibet'), ('sportingbet', 'Sportingbet'), ('comeon', 'ComeOn'), ('sunmaker', 'Sunmaker'), ('bet3000', 'Bet3000'), ('tipico', 'Tipico'), ('xtip', 'X-Tip'), ('betsson', 'Betsson'), ('betfair', 'Betfair')], max_length=50, null=True),
        ),
    ]
