# Generated by Django 3.2.8 on 2021-12-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bookie_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='bookie',
            options={'ordering': ['owner', 'name']},
        ),
    ]
