# Generated by Django 3.2.8 on 2021-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211202_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
