# Generated by Django 3.2.8 on 2022-01-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notifications',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookie',
            name='name',
            field=models.CharField(blank=True, choices=[(None, 'Wettanbieter auswählen'), ('bet-at-home', 'Bet-At-Home'), ('bet365', 'Bet365'), ('betway', 'Betway'), ('bwin', 'Bwin'), ('interwetten', 'Interwetten'), ('unibet', 'Unibet'), ('comeon', 'ComeOn'), ('sunmaker', 'Sunmaker'), ('bet3000', 'Bet3000'), ('tipico', 'Tipico'), ('xtip', 'X-Tip'), ('bildbet', 'BildBet')], max_length=50, null=True),
        ),
    ]
