# Generated by Django 3.2.8 on 2022-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220106_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='notifications',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
