# Generated by Django 3.2.8 on 2022-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
