# Generated by Django 3.2.8 on 2022-01-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_notifications'),
        ('helpcenter', '0010_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
