# Generated by Django 3.2.8 on 2022-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0012_support_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
