# Generated by Django 3.2.8 on 2022-01-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0013_support_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
